In [16]:
# Numpy create a numpy array

import numpy as np

# 1D Array
d1 = np.array([1,2,3,4])

# 2D Array
d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(d1)
print(d2)


[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Shape size and dimensions

# get shape
shape2d = d2.shape

print(shape2d)

# get dim
dim = d2.ndim

print(dim)

# get total number of elements
ele = d2.size

print(ele)

(3, 3)
2
9


In [24]:
# Indexing and Slicing

e = d1[2]

print(e)


# slicing array

sl1 = d1[1:4]

print(sl1)


# indexing 2D array

e2 = d2[1,2]

print(e2)


# slicing 2D array

sl2 = d2[:][:, 1:3]

print(sl2)

3
[2 3 4]
6
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
# Reshaping

reshaped_array = np.array([1,2,3,4,5,6]).reshape(2,3)

print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [29]:
# Mathematical Operations

# element wise addition

sum_np = np.array([1,2,3]) + np.array([2,1,4])

print(sum_np)


# Element-wise multiplication
product_array = np.array([1, 2, 3]) * np.array([4, 5, 6])

print(product_array)

# Dot product of two arrays
dot_product = np.dot(np.array([1, 2, 3]), np.array([4, 5, 6]))

print(dot_product)


[3 3 7]
[ 4 10 18]
32


In [31]:
# Statistical Operations

# mean, mode, std

# Calculate mean of an array
mean_value = np.mean(np.array([1, 2, 3, 4, 5]))

print(mean_value)

# Calculate median of an array
median_value = np.median(np.array([1, 2, 3, 4, 5]))

print(median_value)


# Calculate standard deviation of an array
std_deviation = np.std(np.array([1, 2, 3, 4, 5]))

print(std_deviation)


3.0
3.0
1.4142135623730951


In [33]:
# Higher-Dimensional Array Operations:

# Create a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

sum_axis_0 = np.sum(array_3d, axis=0 )

print(sum_axis_0)

sum_axis_1 = np.sum(array_3d, axis=1 )

print(sum_axis_1)

sum_axis_2 = np.sum(array_3d, axis=2 )

print(sum_axis_2)

[[ 8 10 12]
 [14 16 18]]
[[ 5  7  9]
 [17 19 21]]
[[ 6 15]
 [24 33]]


In [35]:
# Advanced Indexing

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Fancy indexing - selecting specific elements
selected_elements = array_2d[[0, 2], [1, 2]]  # Select elements at (0, 1) and (2, 2)

print(selected_elements)


# Boolean indexing - selecting elements based on a condition
condition = array_2d > 5
elements_greater_than_5 = array_2d[condition]

print(elements_greater_than_5)

[2 9]
[6 7 8 9]
